// <auto-generated />
using System;
using Furni.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Furni.Migrations
{
    [DbContext(typeof(FurniDbContext))]
    [Migration("20251101200449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Furni.Entities.About", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("Furni.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostalCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7eaa7b8a-dea2-4081-91dd-83ff540e780e"),
                            City = "Baku",
                            PostalCode = 1052,
                            Region = "Yasamal",
                            Street = "Tbilisi Avenue 45"
                        });
                });

            modelBuilder.Entity("Furni.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Furni.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Furni.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Furni.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Furni.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("115378e2-fea3-4ed5-a02a-aa732514164a"),
                            Mail = "info@furni.az",
                            Phone = "+994 50 123 45 67"
                        });
                });

            modelBuilder.Entity("Furni.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e75b8e2-b8b4-4956-985f-6c22f37610e4"),
                            Description = "Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada",
                            Title = "We Help You Make Modern Interior Design"
                        });
                });

            modelBuilder.Entity("Furni.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FeatureId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afcdf3e8-83d8-496a-946e-b62b60584748"),
                            Alt = "nordic_chair",
                            ImageType = 0,
                            RelatedEntityId = new Guid("80086632-658a-40b0-b152-a471a7a64df0"),
                            RelatedEntityType = "Product",
                            Url = "/furni/images/product/product-1.png"
                        },
                        new
                        {
                            Id = new Guid("2eb129b8-2521-4b56-b734-888e31f5dbb8"),
                            Alt = "nordic_chair",
                            ImageType = 0,
                            RelatedEntityId = new Guid("b88c6c96-2e03-4100-a364-983a5a08149b"),
                            RelatedEntityType = "Product",
                            Url = "/furni/images/product/product-2.png"
                        },
                        new
                        {
                            Id = new Guid("e8691e2f-3a21-4127-bbc7-fdc4beb70de4"),
                            Alt = "nordic_chair",
                            ImageType = 0,
                            RelatedEntityId = new Guid("81cecee6-b6a8-4bba-a937-e88e40c228a6"),
                            RelatedEntityType = "Product",
                            Url = "/furni/images/product/product-3.png"
                        },
                        new
                        {
                            Id = new Guid("be25a131-f8ab-4157-a243-ad12ebe9020e"),
                            Alt = "nordic_chair",
                            ImageType = 0,
                            RelatedEntityId = new Guid("e40ee004-dccb-42bf-9af0-cf52ff265c9b"),
                            RelatedEntityType = "Product",
                            Url = "/furni/images/product/product-4.png"
                        },
                        new
                        {
                            Id = new Guid("e3cd5177-1b74-43d4-b911-14de2c740371"),
                            Alt = "nordic_chair",
                            ImageType = 0,
                            RelatedEntityId = new Guid("dd2896cf-fcef-45ed-8ae9-93a5d02c662d"),
                            RelatedEntityType = "Product",
                            Url = "/furni/images/product/product-1.png"
                        },
                        new
                        {
                            Id = new Guid("82e63a5e-7d60-460b-8298-a2867a24175b"),
                            Alt = "nordic_chair",
                            ImageType = 0,
                            RelatedEntityId = new Guid("46fd8e61-7670-4037-9ec4-a772f602b27b"),
                            RelatedEntityType = "Product",
                            Url = "/furni/images/product/product-2.png"
                        },
                        new
                        {
                            Id = new Guid("4042b3be-3dad-4f49-9df8-f0ef3ea8c450"),
                            Alt = "nordic_chair",
                            ImageType = 0,
                            RelatedEntityId = new Guid("20bb2db5-43f9-45ae-b74d-541df5d6e75a"),
                            RelatedEntityType = "Product",
                            Url = "/furni/images/product/product-3.png"
                        },
                        new
                        {
                            Id = new Guid("5a9fe4d0-d610-4d10-ab0e-7963c160ff93"),
                            Alt = "nordic_chair",
                            ImageType = 0,
                            RelatedEntityId = new Guid("e40f7ce6-ddfb-4484-8fd7-3a93c456d5be"),
                            RelatedEntityType = "Product",
                            Url = "/furni/images/product/product-4.png"
                        },
                        new
                        {
                            Id = new Guid("efd2ce03-b209-4bbf-8751-7bac09c53ac4"),
                            Alt = "nordic_chair",
                            ImageType = 3,
                            RelatedEntityId = new Guid("4e75b8e2-b8b4-4956-985f-6c22f37610e4"),
                            RelatedEntityType = "Feature",
                            Url = "/furni/images/features/img-grid-1.jpg"
                        },
                        new
                        {
                            Id = new Guid("2710058d-7aa2-42d5-9de3-54d4a197d679"),
                            Alt = "nordic_chair",
                            ImageType = 3,
                            RelatedEntityId = new Guid("4e75b8e2-b8b4-4956-985f-6c22f37610e4"),
                            RelatedEntityType = "Feature",
                            Url = "/furni/images/features/img-grid-2.jpg"
                        },
                        new
                        {
                            Id = new Guid("7ca74e81-a0b7-40df-9773-d9eba4541244"),
                            Alt = "nordic_chair",
                            ImageType = 3,
                            RelatedEntityId = new Guid("4e75b8e2-b8b4-4956-985f-6c22f37610e4"),
                            RelatedEntityType = "Feature",
                            Url = "/furni/images/features/img-grid-3.jpg"
                        },
                        new
                        {
                            Id = new Guid("178145d8-237d-44c5-9ad1-a7ac37d0856a"),
                            Alt = "nordic_chair",
                            ImageType = 1,
                            RelatedEntityId = new Guid("836abebe-b2f0-4a99-b035-c1ce0535d8d0"),
                            RelatedEntityType = "TeamMember",
                            Url = "/furni/images/team_member/person_1.jpg"
                        },
                        new
                        {
                            Id = new Guid("bea822cf-509c-4a64-9fa8-03b67161be56"),
                            Alt = "nordic_chair",
                            ImageType = 1,
                            RelatedEntityId = new Guid("2d9ee73b-8e5e-4fdc-8b11-f8b2ac85d7b4"),
                            RelatedEntityType = "TeamMember",
                            Url = "/furni/images/team_member/person_1.jpg"
                        },
                        new
                        {
                            Id = new Guid("609ca707-ce3c-468a-9a6e-41e343f694b7"),
                            Alt = "nordic_chair",
                            ImageType = 1,
                            RelatedEntityId = new Guid("2a36057b-6060-4c4c-a7cf-bef3891da8f1"),
                            RelatedEntityType = "TeamMember",
                            Url = "/furni/images/team_member/person_1.jpg"
                        },
                        new
                        {
                            Id = new Guid("d8c5b052-88b0-4369-9c47-2373ef7e4fbf"),
                            Alt = "nordic_chair",
                            ImageType = 1,
                            RelatedEntityId = new Guid("ecf3ee48-c608-4c66-be4a-d6aa586f50e9"),
                            RelatedEntityType = "TeamMember",
                            Url = "/furni/images/team_member/person_1.jpg"
                        });
                });

            modelBuilder.Entity("Furni.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Furni.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e61ac57a-e1ad-4995-9166-d3a286d7ac73"),
                            FeatureId = new Guid("4e75b8e2-b8b4-4956-985f-6c22f37610e4"),
                            Text = "Modern design furniture for stylish homes."
                        },
                        new
                        {
                            Id = new Guid("7e352dfd-e936-43d2-96f6-d3c4d39e0c87"),
                            FeatureId = new Guid("4e75b8e2-b8b4-4956-985f-6c22f37610e4"),
                            Text = "High-quality materials with long-lasting durability."
                        },
                        new
                        {
                            Id = new Guid("45407f1d-81bd-404d-b92f-b8775ee99b06"),
                            FeatureId = new Guid("4e75b8e2-b8b4-4956-985f-6c22f37610e4"),
                            Text = "Exclusive discounts on all living room collections."
                        },
                        new
                        {
                            Id = new Guid("2c9ee229-15ab-46bb-9084-1f0ef190765a"),
                            FeatureId = new Guid("4e75b8e2-b8b4-4956-985f-6c22f37610e4"),
                            Text = "Free delivery on orders over 500 AZN."
                        });
                });

            modelBuilder.Entity("Furni.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Furni.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Furni.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80086632-658a-40b0-b152-a471a7a64df0"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        },
                        new
                        {
                            Id = new Guid("b88c6c96-2e03-4100-a364-983a5a08149b"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        },
                        new
                        {
                            Id = new Guid("81cecee6-b6a8-4bba-a937-e88e40c228a6"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        },
                        new
                        {
                            Id = new Guid("e40ee004-dccb-42bf-9af0-cf52ff265c9b"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        },
                        new
                        {
                            Id = new Guid("dd2896cf-fcef-45ed-8ae9-93a5d02c662d"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        },
                        new
                        {
                            Id = new Guid("46fd8e61-7670-4037-9ec4-a772f602b27b"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        },
                        new
                        {
                            Id = new Guid("20bb2db5-43f9-45ae-b74d-541df5d6e75a"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        },
                        new
                        {
                            Id = new Guid("e60070aa-0b4a-42d0-8f8d-0c84806dc10b"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        },
                        new
                        {
                            Id = new Guid("e40f7ce6-ddfb-4484-8fd7-3a93c456d5be"),
                            Description = "The Nordic Chair blends minimalism with comfort, inspired by Scandinavian design principles. Crafted from durable oak wood and upholstered with soft linen fabric, it provides both elegance and support. Its clean lines, natural finish, and ergonomic shape make it perfect for modern homes, cafes, or offices seeking timeless, cozy sophistication.",
                            Name = "Nordic chair",
                            Price = 59m
                        });
                });

            modelBuilder.Entity("Furni.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9de341c-a872-4736-832e-f7340883e762"),
                            Description = "We design personalized furniture based on your taste and space layout.",
                            Title = "Custom Furniture Design"
                        },
                        new
                        {
                            Id = new Guid("6564eb6d-89ee-4ac5-9491-4a6e4d011ffe"),
                            Description = "Our design experts help you choose the perfect combination of colors and furniture.",
                            Title = "Interior Consultation"
                        },
                        new
                        {
                            Id = new Guid("754ba866-d61a-4582-ab70-2ebb926f3ee1"),
                            Description = "We ensure safe delivery and professional assembly of all furniture pieces.",
                            Title = "Delivery & Assembly"
                        },
                        new
                        {
                            Id = new Guid("9db157b1-2563-4d4f-a86e-f4b9f889ca92"),
                            Description = "Our support team assists with maintenance and warranty-related inquiries.",
                            Title = "After-Sales Support"
                        });
                });

            modelBuilder.Entity("Furni.Entities.Slider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SliderImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SliderImageId");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4f9293b-9370-44ea-a561-54609aaca790"),
                            Description = "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.",
                            Page = 1,
                            SliderImageId = new Guid("4de142fb-97f9-4a34-88a6-f3f6d32b17eb"),
                            Tittle = "About Us"
                        },
                        new
                        {
                            Id = new Guid("534105d0-908f-47fa-a2c6-248f6d49ff7d"),
                            Description = "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.",
                            Page = 2,
                            SliderImageId = new Guid("4de142fb-97f9-4a34-88a6-f3f6d32b17eb"),
                            Tittle = "Contact"
                        },
                        new
                        {
                            Id = new Guid("c9b2e447-afb2-4609-a54f-2d8722557707"),
                            Description = "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.",
                            Page = 0,
                            SliderImageId = new Guid("4de142fb-97f9-4a34-88a6-f3f6d32b17eb"),
                            Tittle = "Modern Interior Design Studio"
                        },
                        new
                        {
                            Id = new Guid("4c093d51-7e4b-4788-907d-39337c610a84"),
                            Description = "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.",
                            Page = 3,
                            SliderImageId = new Guid("4de142fb-97f9-4a34-88a6-f3f6d32b17eb"),
                            Tittle = "Services"
                        });
                });

            modelBuilder.Entity("Furni.Entities.SliderImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SliderImage");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4de142fb-97f9-4a34-88a6-f3f6d32b17eb"),
                            Alt = "Modern Nordic Chair in minimal room",
                            Url = "furni/images/sliders/images/couch.png"
                        });
                });

            modelBuilder.Entity("Furni.Entities.SocialMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SocialMedia");
                });

            modelBuilder.Entity("Furni.Entities.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("Furni.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("836abebe-b2f0-4a99-b035-c1ce0535d8d0"),
                            Description = "John leads the company with over 10 years of experience in furniture design and business strategy.",
                            Name = "John",
                            Surname = "Smith",
                            Title = "Founder & CEO"
                        },
                        new
                        {
                            Id = new Guid("2d9ee73b-8e5e-4fdc-8b11-f8b2ac85d7b4"),
                            Description = "Sarah specializes in creating modern and minimalist interior solutions that combine beauty and functionality.",
                            Name = "Sarah",
                            Surname = "Johnson",
                            Title = "Interior Designer"
                        },
                        new
                        {
                            Id = new Guid("2a36057b-6060-4c4c-a7cf-bef3891da8f1"),
                            Description = "Michael manages the marketing strategy and ensures that Furni’s vision reaches customers worldwide.",
                            Name = "Michael",
                            Surname = "Brown",
                            Title = "Marketing Director"
                        },
                        new
                        {
                            Id = new Guid("ecf3ee48-c608-4c66-be4a-d6aa586f50e9"),
                            Description = "Emma ensures a smooth and satisfying experience for every customer, from first contact to after-sales support.",
                            Name = "Emma",
                            Surname = "Davis",
                            Title = "Customer Relations Manager"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Furni.Entities.Cart", b =>
                {
                    b.HasOne("Furni.Entities.AppUser", "AppUser")
                        .WithOne("Cart")
                        .HasForeignKey("Furni.Entities.Cart", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Furni.Entities.CartItem", b =>
                {
                    b.HasOne("Furni.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furni.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Furni.Entities.Image", b =>
                {
                    b.HasOne("Furni.Entities.Feature", null)
                        .WithMany("Image")
                        .HasForeignKey("FeatureId");
                });

            modelBuilder.Entity("Furni.Entities.Offer", b =>
                {
                    b.HasOne("Furni.Entities.Feature", null)
                        .WithMany("Offers")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Furni.Entities.Order", b =>
                {
                    b.HasOne("Furni.Entities.AppUser", "AppUser")
                        .WithOne("Order")
                        .HasForeignKey("Furni.Entities.Order", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Furni.Entities.OrderItem", b =>
                {
                    b.HasOne("Furni.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furni.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Furni.Entities.Product", b =>
                {
                    b.HasOne("Furni.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Furni.Entities.Slider", b =>
                {
                    b.HasOne("Furni.Entities.SliderImage", "SliderImage")
                        .WithMany("Slider")
                        .HasForeignKey("SliderImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SliderImage");
                });

            modelBuilder.Entity("Furni.Entities.TeamMember", b =>
                {
                    b.HasOne("Furni.Entities.Image", "ProfilePhoto")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("ProfilePhoto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Furni.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Furni.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Furni.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Furni.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furni.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Furni.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Furni.Entities.AppUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Furni.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Furni.Entities.Feature", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Furni.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Furni.Entities.SliderImage", b =>
                {
                    b.Navigation("Slider");
                });
#pragma warning restore 612, 618
        }
    }
}
